# -*- coding: utf-8 -*-
{
    'name': 'Personnalisation du module CRM',
    'version': '1.0',
    'description': 'Personnalisation du module CRM en ajoutant les champs  contacté par IGY, moyen et sources dans la vue formulaire situant sous le champ étiquettes',
    'author': 'Ingenosya',
    'sequence':1,
    'website': 'www.ingenosya.com',
    'depends': [
        'crm', 'base', 'utm', 'kanban_draggable', 'odoo_email_cc_bcc-12', 'igy_import_crm', 'mass_mailing', 'mass_mailing_crm'
    ],
    # always loaded
    'data': [
        'security/ir.model.access.csv',
        'security/res_groups.xml',
        'data/crm_global_stage.xml',
        'data/utm_data.xml',
        'data/partner_activity.xml',
        'data/data.xml',
        'data/ir_cron.xml',
        'data/mail_template_data.xml',
        'data/send_mail.xml',
        'data/mail_activity_type.xml',
        'data/mass_mailing_cron.xml',
        'view/crm_lead_quick_create_form_view.xml',
        'view/crm_global_stage_view.xml',
        'view/crm_stage_two.xml',
        'data/crm_stage.xml',
        'view/crm_lead_global_view.xml',
        'view/utm_view.xml',
        'view/crm_lead_tree_inherit.xml',
        'view/crm_lead_piste_view.xml',
        'view/crm_lead_opportunity_view.xml',
        'view/crm_lead_tender_view.xml',
        'view/res_partner_activity_view.xml',
        'view/crm_lead_analysies.xml',
        'view/menu_items.xml',
        'view/res_partner_form.xml',
        'view/crm_view_pistes.xml',
        'view/crm_count_mail_view.xml',
        'view/assets.xml',
        'data/menu_function.xml',
        'wizard/mail_compose.xml',
        'view/mass_mailing_form_inherit.xml',
        'data/ir_actions_server_data.xml',
        'wizard/update_tag_wizard.xml',
        'wizard/update_stage_wizard.xml',
        'view/mass_mailing_cold_views.xml',
        'data/res_partner_data.xml',
        'view/crm_setting_view.xml'
    ],
    
    'installable': True,
    'application': False,
}
